### ISSUE TITLE
Master Checklist

### ISSUE THREAD

**Issue by DenisKent** [FACN4/Week6-Rate-My-GIT#1]
- [x] Simple web app with a node server and a database
- [x] Your database comes with a schema, which should be documented in your readme (along with any other architectural decisions)
- [x] Database hosted on Heroku, or locally
- [x] Build script for your database
- [x] Security concerns appropriately considered (you must protect against script injections!)
- [x] Good test coverage both server- and client-side #8 
- [x] Content dynamic, but DOM manipulation kept to a minimum
- [x] Mobile-first design
- [x] Clear user journey (document the user journey in your readme)
