### ISSUE TITLE
quickfire to-do's

### ISSUE THREAD

**Issue by DenisKent** [FACN4/Week6-Rate-My-GIT#26]
- [x]  CSS, images same height and width #20 
- [x] HTML remove Denis and Sol and replace with blank space with appropriate width #21
- [ ] HTML add like button #22
- [x] DOM update username above picture #23
- [x] DOM walls front end #24
- [x] JS finish post request chain #25
- [x] Testing across the project #27
- [x] Finish CSS styling #28
- [x] Do readme file (include user journey) #29
- [ ] Do security audit #30
